### PR TITLE
Refactor to use Gatsby

### PR DESCRIPTION
**Pull request by neb42**
This PR refactors the codebase to use [Gatsby](https://www.gatsbyjs.org/) to generate static html/js/css at build time, removing data fetching on page load. Alongside this changes have been made to provide a more complete experience for users with javascript disabled.

### CODE REVIEW

**Comment by neb42** [comment]
This closes issue #15

**Comment by neb42** [comment]
Also fixes issue #43

**Comment by neb42** [comment]
This will require changes to the build/etl pipeline.

After running `yarn build` it is now the `public` directory that should be deployed.

Whenever new data is published the CI pipeline should be ran to build and deploy the site.

**Comment by xenatisch** [comment]
[Does not work with javascript turned off. We need a fallback option.](https://trello.com/c/mS3s4WiE/134-does-not-work-with-javascript-turned-off-we-need-a-fallback-option)

**Comment by xenatisch** [comment]
[manifest.json is missing on website](https://trello.com/c/26CtJR7g/278-manifestjson-is-missing-on-website)

**Comment by umaar** [comment]
Looks great! Currently, I still see the "You need to enable JavaScript to run this app." message, does this feature need deploying?

**Pull request merged**
