### PR TITLE
Essential improvements and new features

### PR DESCRIPTION
**Pull request by xenatisch**
Implement static hard links to download the latest data as CSV (issue #14)
Improves zoom on maps (issue #34)
Changes "Country" and "Country - UK" area types respectively to "Nation" and "UK" in the CSV files.

### CODE REVIEW

**Comment by xenatisch** [comment]
[Feature: A permanent URL or CSV link rather than a dynamically generated one](https://trello.com/c/PvQicSQI/260-feature-a-permanent-url-or-csv-link-rather-than-a-dynamically-generated-one)

**Comment by xenatisch** [comment]
[Add min and max zoom to the map, improve default centroid/zoom](https://trello.com/c/JgP6jvZv/264-add-min-and-max-zoom-to-the-map-improve-default-centroid-zoom)

**Comment by xenatisch** [comment]
[Change countries to nations in page and data](https://trello.com/c/ZHVs4NOz/270-change-countries-to-nations-in-page-and-data)

**Comment by n34l** [comment]
Issues resolved.

**Pull request merged**
