### PR TITLE
Fixes reset button not linking to the correct path

### PR DESCRIPTION
**Pull request by beawitcht**

### CODE REVIEW

**Review by xenatisch — COMMENTED** [review]
To be fair, it's a decent workaround, but I'm more of the opinion that we should change this to "Reset to England", and manually add "United Kingdom" to the menu. 

It makes more sense as the UK is no longer the root page of the navigated path, and the intention of the _reset_ button is to go back to the root. That's specially useful on mobile devices. It'll take a bit more work though.

I'm not married to the idea, but I've already discussed it with Dave. Would love to hear your thoughts.

**Comment by DaveJephson** [comment]
Maybe the fix that Bea has done is something that can be implemented quickly to keep things working as they should. Then Pouria can look to implement the more thorough change (adding UK to the menu etc) without any time pressure?

**Comment by beawitcht** [comment]
> To be fair, it's a decent workaround, but I'm more of the opinion that we should change this to "Reset to England", and manually add "United Kingdom" to the menu.
> 
> It makes more sense as the UK is no longer the root page of the navigated path, and the intention of the _reset_ button is to go back to the root. That's specially useful on mobile devices. It'll take a bit more work though.
> 
> I'm not married to the idea, but I've already discussed it with Dave. Would love to hear your thoughts.

That makes sense to me, maybe as an intermediary, I could change the text to 'Set to UK' for now? then I can add expanding the dropdown to include UK + changing the button to 'Reset to England' to my to do list

**Comment by DaveJephson** [comment]
Sounds like a good idea to me!

**Comment by DaveJephson** [comment]
I've also spotted another behaviour that isn't ideal - if you set an area on a details page, for example a local authority, and then click on the left hand menu to another details page, it is the UK that is shown, whereas now we expect it to be England.

**Comment by beawitcht** [comment]
> I've also spotted another behaviour that isn't ideal - if you set an area on a details page, for example a local authority, and then click on the left hand menu to another details page, it is the UK that is shown, whereas now we expect it to be England.

well spotted! fixed in this PR now too

**Review by xenatisch — APPROVED** [review]

**Pull request merged**
