### PR TITLE
Cookie preferences

### PR DESCRIPTION
**Pull request by johnbenjaminphe**
The changes for cookie preferences has been implemented and ready to be merged to the development branch.

### CODE REVIEW

**Comment by Ha-san-ali** [comment]
[Cookies preferences page and different banner text](https://trello.com/c/JVvSdVRy/233-cookies-preferences-page-and-different-banner-text)

**Comment by xenatisch** [comment]
The branch will be merged once PR #48 is merged to the `master` branch and released. 

Thank you @johnbenjaminphe for the great work.

**Comment by neb42** [comment]
`src/App.js` should be deleted as this no longer exists with gatsby

**Comment by xenatisch** [comment]
@johnbenjaminphe Could you please look into @neb42's comment?

**Comment by johnbenjaminphe** [comment]
@neb42, @xenatisch 

src/App.js file is now deleted.

**Comment by xenatisch** [comment]
@neb42 Are you satisfied with the change?

**Comment by johnbenjaminphe** [comment]
The update for cookie preferences is now done.

**Pull request merged**
